Gsn-ReclameAli/Models/Context/GsnReclameAliContext.cs
using Gsn_ReclameAli.Mappings;
using Gsn_ReclameAli.Models;
using Microsoft.EntityFrameworkCore;

namespace Gsn_ReclameAli.DataContext
{
    public class GsnReclameAliContext: DbContext
    {
        public GsnReclameAliContext(DbContextOptions<GsnReclameAliContext> options) : base(options)
        {
            ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
            ChangeTracker.AutoDetectChangesEnabled = false;

        }

        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<ProblemaModel> Problema { get; set; }
        public DbSet<EnderecoModel> Endereco { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new UsuarioMap());
            modelBuilder.ApplyConfiguration(new EnderecoMap());
            modelBuilder.ApplyConfiguration(new ProblemaMap());


        }
    }
}

Gsn-ReclameAli/Models/EnderecoModel.cs
using System.ComponentModel.DataAnnotations;

namespace Gsn_ReclameAli.Models
{
    public class EnderecoModel
    {
         public int EnderecoId { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Cep { get; set; }
        public string Estado { get; set; }
        public int ProblemaId { get; set; }
        public virtual List<ProblemaModel> Problema { get; set; }

    }
}

Gsn-ReclameAli/Models/ErrorViewModel.cs
namespace Gsn_ReclameAli.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Gsn-ReclameAli/Models/ProblemaModel.cs
namespace Gsn_ReclameAli.Models
{
    public class ProblemaModel
    {
        
        public int ProblemaId { get; set; } 

        public string Titulo { get; set; }

        public string Descricao { get; set; }   

        public virtual EnderecoModel Endereco { get; set; }    
         
     
    }
}

Gsn-ReclameAli/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;

namespace Gsn_ReclameAli.Models
{
    public class Usuario
    {
        public int UsuarioId{ get; set; }
        public string? Nome { get; set; }
        public string Email { get; set; }
        public string? Senha { get; set; }

    }
}

Gsn-ReclameAli/Controllers/HomeController.cs
using Gsn_ReclameAli.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Gsn_ReclameAli.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SobreNos()
        {
            return View();
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Gsn-ReclameAli/Controllers/ProblemaController.cs
using Gsn_ReclameAli.Interfaces;
using Gsn_ReclameAli.Models;
using Microsoft.AspNetCore.Mvc;

namespace Gsn_ReclameAli.Controllers
{
    public class ProblemaController : Controller
    {
        private readonly IProblemaService _problemaService;
        public ProblemaController(IProblemaService problemaService)
        {
            _problemaService = problemaService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Salvar(ProblemaModel problema)
        {
            _problemaService.SalvarProblemaAsync(problema);
            return default;
        }


        [HttpGet]
        public IActionResult ListarProblemas(ProblemaModel problema)
        {
            _problemaService.SalvarProblemaAsync(problema);
            return default;
        }
    }
}

Gsn-ReclameAli/Controllers/UsuarioController.cs
using Gsn_ReclameAli.Interfaces;
using Gsn_ReclameAli.Models;
using Gsn_ReclameAli.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using System.Security.Claims;

namespace Gsn_ReclameAli.Controllers
{
    public class UsuarioController : Controller
    {

        private readonly IUsuarioService _usuarioService;
        public UsuarioController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SalvarUsuarioAsync(Usuario usuario)
        {
            try
            {
                var result = await _usuarioService.SalvarUsuarioAsync(usuario);
                //if(result.StatusCode )
                //{

                //}
                return RedirectToAction("Index", "Usuario");
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Logar(string email, string senha)
        {
            var usuario = await _usuarioService.AutenticarUsuarioAsync(email, senha);
            if (usuario.StatusCode == HttpStatusCode.OK)
            {
                var claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier, usuario.Model.UsuarioId.ToString()),
                    new Claim(ClaimTypes.Name, usuario.Model.Nome),
                    new Claim(ClaimTypes.UserData, JsonConvert.SerializeObject(usuario.Model))
                };
                var identity = new ClaimsIdentity(claims, "BRBViagensAuth");
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync("ReclameAliAuth", principal);
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

Gsn-ReclameAli/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section class="hero-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 col-md-12 col-12">
                <div class="hero-content">
                    <h4 class="wow fadeInUp" data-wow-delay=".2s">We Are Creative Digital Agency</h4>
                    <h1 class="wow fadeInUp" data-wow-delay=".4s">Strategic Concepts For Businesses.</h1>
                    <p class="wow fadeInUp" data-wow-delay=".6s">
                        Invest your spare change in Bitcoin and save
                        with<br> crypto to e arn interest in real time.
                    </p>
                    <div class="button wow fadeInUp" data-wow-delay=".8s">
                        <a href="@Url.Action("SobreNos","Home")" class="btn ">Discover More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-12">
                <div class="hero-image">
                    <img class="main-image" src="~/images/hero/hero-image.png" alt="#">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Hero Area -->
<!-- Start Services Area -->
<div class="services section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <h2 class="wow fadeInUp" data-wow-delay=".2s">O que desejar relatar</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".2s">
                <div class="single-service">
                    <a href="@Url.Action("Index","Problema")">
                        <div class="main-icon">
                            <img class="main-image" src="~/images/buraco.png" alt="#" />
                        </div>
                        <h4 class="text-title">Buraco na via</h4>
                        <p>
                            Informe buracos na via para que as autoridades responsaveis
                        </p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".4s">
                <div class="single-service">
                    <a href="@Url.Action("Index","Problema")">
                        <div class="main-icon">
                            <img class="main-image" src="~/images/animalVia.png alt="#">
                        </div>
                        <h4 class="text-title">Carro Parado Na Via</h4>
                        <p>
                            Não deixe de nos avisar sobre carros parados na via,para mantermnos todos os motoristas em alerta
                        </p>
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".6s">
                <div class="single-service">
                    <a href="@Url.Action("Index","Problema")">
                        <div class="main-icon">
                            <img class="main-image" src="~/images/acidente.png" alt="#">
                        </div>
                        <h4 class="text-title">Acidente Na via</h4>
                        <p>
                            Nós informe sobre acidentes na via para que ou outros não peguem trânsito.
                        </p>
                    </a>
                </div>

            </div>

        </div>
    </div>
</div>

Gsn-ReclameAli/Views/Home/SobreNos.cshtml
@{
    ViewData["Title"] = "Sobre Nós";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="preloader">
    <div class="preloader-inner">
        <div class="preloader-icon">
            <span></span>
            <span></span>
        </div>
    </div>
</div>

<div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 offset-lg-3 col-md-12 col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">About Us</h1>
                    <ul class="breadcrumb-nav">
                        <li> <a class="btn" href="@Url.Action("Index","Home")">Home</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="about section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-12">
                <div class="image wow fadeInLeft" data-wow-delay=".2s">
                    <img src="assets/images/about/about-image.jpg" alt="#">
                </div>
            </div>
            <div class="col-lg-6 col-12">
                <div class="content wow fadeInRight" data-wow-delay=".4s">
                    <h4>DECENTRALISED ECONOMY</h4>
                    <h2>We’ve built a platform to buy and sell shares.</h2>
                    <p>
                        Spend real fights effective anything extra by leading. Mouthwatering leading how real formula
                        also locked-in have can mountain thought. Jumbo plus shine sale.
                    </p>
                    <div class="list">
                        <div class="single-list">
                            <div class="list-icon">
                                <i class="lni lni-checkmark"></i>
                            </div>
                            <h4>Digital Marketing</h4>
                            <p>Quis autem vel eum reprehenderit</p>
                        </div>
                        <div class="single-list">
                            <div class="list-icon">
                                <i class="lni lni-checkmark"></i>
                            </div>
                            <h4>Graphics Desing</h4>
                            <p>Quis autem vel eum reprehenderit</p>
                        </div>
                        <div class="single-list">
                            <div class="list-icon">
                                <i class="lni lni-checkmark"></i>
                            </div>
                            <h4>Consulting Service</h4>
                            <p>Quis autem vel eum reprehenderit</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="services section">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-title">
                    <h3 class="wow zoomIn" data-wow-delay=".2s">What we offer</h3>
                    <h2 class="wow fadeInUp" data-wow-delay=".4s">Our Services</h2>
                    <p class="wow fadeInUp" data-wow-delay=".6s">
                        There are many variations of passages of Lorem
                        Ipsum available, but the majority have suffered alteration in some form.
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".2s">
                <div class="single-service">
                    <div class="main-icon">
                        <i class="lni lni-grid-alt"></i>
                    </div>
                    <h4 class="text-title">Brand Identity Design</h4>
                    <p>
                        Invest in Bitcoin on the regular or save with one of the highest interest rates on the
                        market.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".4s">
                <div class="single-service">
                    <div class="main-icon">
                        <i class="lni lni-keyword-research"></i>
                    </div>
                    <h4 class="text-title">Digital Marketing</h4>
                    <p>
                        Invest in Bitcoin on the regular or save with one of the highest interest rates on the
                        market.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".6s">
                <div class="single-service">
                    <div class="main-icon">
                        <i class="lni lni-vector"></i>
                    </div>
                    <h4 class="text-title">Design and Development</h4>
                    <p>
                        Invest in Bitcoin on the regular or save with one of the highest interest rates on the
                        market.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".2s">
                <div class="single-service">
                    <div class="main-icon">
                        <i class="lni lni-book"></i>
                    </div>
                    <h4 class="text-title">IT Consulting Service</h4>
                    <p>
                        Invest in Bitcoin on the regular or save with one of the highest interest rates on the
                        market.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".4s">
                <div class="single-service">
                    <div class="main-icon">
                        <i class="lni lni-cloud-network"></i>
                    </div>
                    <h4 class="text-title">Cloud Computing</h4>
                    <p>
                        Invest in Bitcoin on the regular or save with one of the highest interest rates on the
                        market.
                    </p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".6s">
                <div class="single-service">
                    <div class="main-icon">
                        <i class="lni lni-display-alt"></i>
                    </div>
                    <h4 class="text-title">Graphics Design</h4>
                    <p>
                        Invest in Bitcoin on the regular or save with one of the highest interest rates on the
                        market.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="call-action bg-white">
    <div class="container">
        <div class="inner-content">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-7 col-12">
                    <div class="text">
                        <h2>
                            You are using free
                            <br> <span>Lite version of Craft.</span>
                        </h2>
                        <p style="display: block;margin-top: 10px;">
                            Please, purchase full version of the template to
                            get all pages,
                            features and commercial license.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5 col-12">
                    <div class="button">
                        <a href="#" class="btn">
                            Buy Pro Version
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Gsn-ReclameAli/Views/Problema/Index.cshtml
@model Gsn_ReclameAli.Models.ProblemaModel


@{
    ViewData["Title"] = "Cadastro de Problema";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="preloader">
    <div class="preloader-inner">
        <div class="preloader-icon">
            <span></span>
            <span></span>
        </div>
    </div>
</div>
<div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 offset-lg-3 col-md-12 col-12">
                <div class="breadcrumbs-content">
                    <h1 class="page-title">Cadastro de Incidentente</h1>
                    <ul class="breadcrumb-nav">
                        <li> <a class="btn" href="@Url.Action("Index","Home")">Home</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<section class="about section">
    <div class="container">
        <div class="row align-items-center">

            <div class="row mb-4">

                @using (Html.BeginForm("Salvar", "Problema", FormMethod.Post, new { @class = "contact-from form-valide" }))
                {
                    <div class="form-control">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-outline">
                                    <label>Qual Problema Você deseja Relatar?</label>
                                    @Html.TextBoxFor(p => p.Titulo ,new { @class="form-control" ,@placeholder = "Que Problema Você deseja Relatar", required="required"} )
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-outline">
                                    <label>Descreva o Problema</label>
                                    @Html.TextBoxFor(p => p.Descricao ,new {@class="form-control", @placeholder = "Descreva o Problema", required="required"} )
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-outline">
                                    <label>Rua</label>
                                    @Html.TextBoxFor(p => p.Endereco.Rua ,new {@class="form-control", @placeholder = "Digite a Rua", required="required"} )
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-outline">
                                    <label>Bairro</label>
                                    @Html.TextBoxFor(p => p.Endereco.Bairro ,new {@class="form-control", @placeholder = "Digite o Bairro", required="required"} )
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-outline">
                                    <label>Cep</label>
                                    @Html.TextBoxFor(p => p.Endereco.Cep ,new {@class="form-control", @placeholder = "Digite o Cep", required="required"} )
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-outline">
                                    <label>Cidade</label>
                                    @Html.TextBoxFor(p => p.Endereco.Cidade ,new { @class="form-control", @placeholder = "Digite a Cidade", required="required"} )
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-outline">
                                    <label>Estado</label>
                                    @Html.TextBoxFor(p => p.Endereco.Estado ,new {@class="form-control", @placeholder = "Digite o Estado", required="required"} )
                                </div>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <button class="btn-outline-primary" type="submit" name="submit" value="Salvar">Salvar</button>
                            <br>

                        </div>
                        <a class="d-flex justify-content-center" href="@Url.Action("Index","Home")">
                            Voltar
                        </a>
                    </div>

                }
            </div>
        </div>
    </div>


</section>

Gsn-ReclameAli/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gsn_ReclameAli</title>
    <link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/dist/css/bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/site.css")" asp-append-version="true" />
    <link rel="stylesheet" href="@Url.Content("~/Gsn_ReclameAli.styles.css")" asp-append-version="true" />

    <link rel="icon" type="image/png" href="~/images/favicon.png">
    <link rel="stylesheet" href="@Url.Content("~/css/bootstrap.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/LineIcons.3.0.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/animate.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/tiny-slider.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/glightbox.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/css/main.css")" />
  


</head>
<body>
       <partial name="~/Views/Shared/_Partial/Header.cshtml" />

    @RenderBody()

    <a href="#" class="scroll-top">
        <i class="lni lni-chevron-up"></i>
    </a>
    <footer class="footer-top">
        <div class="copyright-area">
            <div class="container">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-12">
                            <p class="copyright-text">© 2023 Gsn Reclame Ali - Todos os direitos reservados</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="@Url.Content("~/lib/jquery/dist/jquery.min.js")"></script>
    <script src="@Url.Content("~/lib/bootstrap/dist/js/bootstrap.bundle.min.js")"></script>
    <script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>
    <script src="@Url.Content("~/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/js/wow.min.js")"></script>
    <script src="@Url.Content("~/js/tiny-slider.js")"></script>
    <script src="@Url.Content("~/js/glightbox.min.js")"></script>
    <script src="@Url.Content("~/js/count-up.min.js")"></script>
    <script src="@Url.Content("~/js/imagesloaded.min.js")"></script>
    <script src="@Url.Content("~/js/isotope.min.js")"></script>
    <script src="@Url.Content("~/js/main.js")"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Gsn-ReclameAli/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Slide Navbar</title>
    <link rel="stylesheet" type="text/css" href="slide navbar style.css">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="@Url.Content("~/css/login.css")" />

</head>
<body>
    <div class="main">
        <input type="checkbox" id="chk" aria-hidden="true">

        @RenderBody()

    </div>
</body>
</html>

Gsn-ReclameAli/Views/Shared/_Partial/Header.cshtml
@using System.Security.Claims;
@using Gsn_ReclameAli.Common
@{
    var nomeCompleto = Context.User.GetNomeUsuario();
}
<header class="header navbar-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="nav-inner">
                    <!-- Start Navbar -->
                    <nav class="navbar navbar-expand-lg">

                        <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                            <ul id="nav" class="navbar-nav ms-auto">
                                <li class="nav-item">
                                    <a class="btn" href="@Url.Action("Index","Home")">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn" href="@Url.Action("SobreNos","Home")">Sobre nós</a>
                                </li>

                                <li class="nav-item">
                                    <a href="contact.html" aria-label="Toggle navigation">Contact</a>
                                </li>
                            </ul>
                        </div> <!-- navbar collapse -->
                        @if (string.IsNullOrEmpty(nomeCompleto))
                        {
                            <div class="button">
                                <a class="btn" href="@Url.Action("Index","Usuario")">Login</a>
                            </div>
                        }
                        else
                        {
                            <div class="">
                                <span>@nomeCompleto</span>
                            </div>
                        }
                    </nav>
                    <!-- End Navbar -->
                </div>
            </div>
        </div> <!-- row -->
    </div>
</header>

Gsn-ReclameAli/Views/Usuario/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}



<div class="signup">
    
    @using (Html.BeginForm("SalvarUsuario", "Usuario", FormMethod.Post))
    {
        <label for="chk" aria-hidden="true">Cadastro</label>
        <input type="text" name="nome" id="nome" placeholder="Nome de usuário" required="">
        <input type="email" name="email" id="email" placeholder="E-mail" required="">
        <input type="password" name="senha" id="senha" placeholder="Digite a Senha" required="">
        
        <button type="submit">Sign up</button>
        <button><a class="col-sn-3" href="@Url.Action("Index","Home")">Voltar</a></button>
       
    }
</div>

<div class="login">
    @using (Html.BeginForm("Logar", "Usuario", FormMethod.Post))
    { 
    <label for="chk" aria-hidden="true">Login</label>
    <input type="email" name="email" id="email" placeholder="E-mail" required="">
    <input type="password" name="senha" id="senha" placeholder="Senha" required="">
   
    <button type="submit">Login</button>
    <button><a class="col-sn-3" href="@Url.Action("Index","Home")">Voltar</a></button>
    
    }
</div>